export const Icons = {
  Business: require("../src/Icons/Business.png"),
  ExtraIncome: require("../src/Icons/ExtraIncome.png"), 
  Gifts: require("../src/Icons/Gifts.png"), 
  Loans: require("../src/Icons/Loans.png"), 
  Others: require("../src/Icons/Others.png"), 
  Salary: require("../src/Icons/Salary.png"), 
  Beatuy: require("../src/Icons/Beatuy.png"), 
  Bills: require("../src/Icons/Bills.png"), 
  Debts: require("../src/Icons/Debts.png"), 
  Education: require("../src/Icons/Education.png"), 
  Entertainment: require("../src/Icons/Entertainment.png"), 
  Family: require("../src/Icons/Family.png"), 
  FoodAndDrink: require("../src/Icons/FoodAndDrink.png"), 
  Health: require("../src/Icons/Health.png"), 
  Home: require("../src/Icons/Home.png"), 
  Personal: require("../src/Icons/Personal.png"), 
  Pets: require("../src/Icons/Pets.png"),
  Provisions: require("../src/Icons/Provisions.png"), 
  Shopping: require("../src/Icons/Shopping.png"), 
  Transportation: require("../src/Icons/Transportation.png")
}